data:
  csv_path: "./data/processed/eclektic_long_subset.csv"
  max_examples: 50

eval:
  source_lang: "en"
  target_lang: "fr"

models:
  tested_model: "openai/gpt-4o-mini"
  judge_model:  "google/gemini-1.5-flash"

decode:
  temperature: 0.0
  max_tokens: 128

artifacts_dir: "./artifacts"
