data:
  csv_path: "../data/processed/eclektic_long_subset.csv"
  max_examples: null

eval:
  source_lang: "en"
  target_lang: "he"

models:
  tested_model: "gpt-4o"
  judge_model:  "gpt-5"

decode:
  temperature: 1
  max_tokens: 128

artifacts_dir: "./artifacts"
